# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# 
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "backend/package.json" }}
      - run: cd backend && yarn install
      - save_cache:
          paths:
            - backend/node_modules
          key: v1-dependencies-{{ checksum "backend/package.json" }}

  test:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "backend/package.json" }}
      - run: cd backend && yarn install
      - run: cd backend && yarn test

  deploy:
    docker:
      - image: circleci/node:9.6.1
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "SHA256:G9r3ZDt/S1SeC4HfgZiJAZ5SPoCx261JbMZSsmlVyJc K@ASUS-K"
      - run:
          name: Build Angular
          command: cd frontend && npm i -g @angular/cli && ng build --prod -op ../backend/assets
      - run:
          name: Deploy Master to Heroku
          command: |
            rm -r frontend
            mv backend/{.[!.],}* ./
            git add -A
            git config --global user.email "git@heroku.com"
            git config --global user.name "git@heroku.com"
            git commit -m "deploy heroku"
            git push --force git@heroku.com:tdt4242-group2.git HEAD:refs/heads/master
            heroku restart -a tdt4242-group2

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - heroku-deploy
